export enum DoctorDesignation {
    CONSULTANT = 'CONSULTANT',
    SENIOR_CONSULTANT = 'SENIOR_CONSULTANT',
    JUNIOR_CONSULTANT = 'JUNIOR_CONSULTANT',
    RESIDENT = 'RESIDENT',
    SENIOR_RESIDENT = 'SENIOR_RESIDENT',
    JUNIOR_RESIDENT = 'JUNIOR_RESIDENT',
    MEDICAL_OFFICER = 'MEDICAL_OFFICER',
    REGISTRAR = 'REGISTRAR',
    SPECIALIST = 'SPECIALIST',
    SURGEON = 'SURGEON',
    HOD = 'HEAD_OF_DEPARTMENT',
  }